'''Application Constants'''

PAGE_NAME = 'page_name'
TITULO = 'titulo'
USER_ID = 'user_id'
TYPE = 'type'
TYPE_VALUE = 'opportunity'
EMPRESA_KEY = 'empresa'
DB_KEY = 'db'
ID_KEY = 'id'
USUARIO_LEAD_KEY = 'usuario_lead'
AUTHORIZATION = 'Authorization'
GET_METHOD = 'GET'
POST_METHOD = 'POST'
USERNAME = 'username'
PASSWORD = 'password'
COD_TEL = 'cod_tel'
COD_CEL = 'cod_cel'